import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  // if ('serviceWorker' in navigator) {
  //   navigator.serviceWorker.register('/service-worker.js') // This path is relative to the origin
  //     .then(function (registration) {
  //       console.log('Service Worker registered with scope:', registration.scope);
  //     }).catch(function (error) {
  //       console.log('Service Worker registration failed:', error);
  //     });
  // }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
